---
- name: "ldap: create configuration"
  template:
    src: "postfix/ldap/{{ item.type }}"
    dest: "{{ item.path | default('/etc/postfix/maps/'+(item.name|default())) }}"
    owner: postfix
    group: postfix
    mode: ug=r,o-rwx
  with_items: "{{ mta_ldaps }}"
  notify:
  - reload postfix
